services:
  db:
    image: postgres:15-alpine
    container_name: albaraka-db
    restart: always
    environment:
      POSTGRES_DB: albaraka_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - albaraka-network


  minio:
    image: minio/minio
    container_name: albaraka-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - albaraka-network

  app:
    build: .
    container_name: albaraka-app
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/albaraka_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=documents
    networks:
      - albaraka-network

networks:
  albaraka-network:
    driver: bridge

volumes:
  postgres_data: