spring.datasource.url=jdbc:postgresql://localhost:5432/albaraka_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


minio.url=http://albaraka-minio:9000
minio.accessKey=${MINIO_ROOT_USER}
minio.secretKey=${MINIO_ROOT_PASSWORD}
minio.bucketName=albaraka-bucket

app.frontend.url=http://localhost:4200

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${AI_OPENAI_API_KEY}
spring.ai.openai.chat.options.model=google/gemini-flash-1.5-exp:free

security.jwt.secret=${JWT_SECRET}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}


spring.security.oauth2.client.registration.facebook.client-id=${FB_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FB_SECRET}
spring.security.oauth2.client.registration.facebook.scope=${FB_SCOPE}
